import * as LucideIcons from 'lucide-react-native';

// Define IconName type based on available icons
type IconName = keyof typeof LucideIcons;

export interface AudioCategory {
  id: string;
  name: string;
  icon: IconName;
}

export interface AudioEffect {
  id: string;
  name: string;
  categoryId: string;
  description: string;
}

export const audioCategories: AudioCategory[] = [
  { id: 'epic', name: 'EPIC', icon: 'Flame' },
  { id: 'cartoon', name: 'CARTOON', icon: 'Laugh' },
  { id: 'horror', name: 'HORROR', icon: 'Skull' },
  { id: 'sport', name: 'SPORT', icon: 'Trophy' },
  { id: 'tech', name: 'TECH', icon: 'Cpu' },
  { id: 'robot', name: 'ROBOT', icon: 'Bot' },
  { id: 'film', name: 'FILM', icon: 'Clapperboard' },
  { id: 'dark', name: 'DARK', icon: 'Moon' },
  { id: 'pop', name: 'POP', icon: 'Music' },
  { id: 'weird', name: 'WEIRD', icon: 'Sparkles' },
];

export const audioEffects: AudioEffect[] = [
  // EPIC category
  { id: 'epic-1', name: 'Epic Orchestra', categoryId: 'epic', description: 'Dramatic orchestral hit' },
  { id: 'epic-2', name: 'Epic Drums', categoryId: 'epic', description: 'Powerful drum sequence' },
  { id: 'epic-3', name: 'Epic Brass', categoryId: 'epic', description: 'Heroic brass section' },
  { id: 'epic-4', name: 'Epic Choir', categoryId: 'epic', description: 'Majestic choir vocals' },
  { id: 'epic-5', name: 'Epic Strings', categoryId: 'epic', description: 'Intense string section' },
  { id: 'epic-6', name: 'Epic Percussion', categoryId: 'epic', description: 'Thunderous percussion' },
  { id: 'epic-7', name: 'Epic Rise', categoryId: 'epic', description: 'Dramatic rising tension' },
  { id: 'epic-8', name: 'Epic Fall', categoryId: 'epic', description: 'Powerful descending effect' },
  { id: 'epic-9', name: 'Epic Impact', categoryId: 'epic', description: 'Massive impact sound' },
  { id: 'epic-10', name: 'Epic Trailer', categoryId: 'epic', description: 'Movie trailer style hit' },
  { id: 'epic-11', name: 'Epic Battle', categoryId: 'epic', description: 'Intense battle sounds' },
  { id: 'epic-12', name: 'Epic Victory', categoryId: 'epic', description: 'Triumphant victory theme' },
  { id: 'epic-13', name: 'Epic Defeat', categoryId: 'epic', description: 'Somber defeat theme' },
  { id: 'epic-14', name: 'Epic Adventure', categoryId: 'epic', description: 'Adventurous theme' },
  { id: 'epic-15', name: 'Epic Mystery', categoryId: 'epic', description: 'Mysterious atmosphere' },
  { id: 'epic-16', name: 'Epic Horror', categoryId: 'epic', description: 'Horrifying epic sound' },
  { id: 'epic-17', name: 'Epic Fantasy', categoryId: 'epic', description: 'Magical fantasy theme' },
  { id: 'epic-18', name: 'Epic Sci-Fi', categoryId: 'epic', description: 'Futuristic sci-fi sound' },
  { id: 'epic-19', name: 'Epic Western', categoryId: 'epic', description: 'Wild west theme' },
  { id: 'epic-20', name: 'Epic Medieval', categoryId: 'epic', description: 'Medieval atmosphere' },
  
  // CARTOON category
  { id: 'cartoon-1', name: 'Boing', categoryId: 'cartoon', description: 'Classic spring bounce' },
  { id: 'cartoon-2', name: 'Slip', categoryId: 'cartoon', description: 'Slipping sound effect' },
  { id: 'cartoon-3', name: 'Pop', categoryId: 'cartoon', description: 'Bubble pop sound' },
  { id: 'cartoon-4', name: 'Whistle', categoryId: 'cartoon', description: 'Falling whistle' },
  { id: 'cartoon-5', name: 'Splat', categoryId: 'cartoon', description: 'Splatting sound' },
  { id: 'cartoon-6', name: 'Stretch', categoryId: 'cartoon', description: 'Stretching sound' },
  { id: 'cartoon-7', name: 'Twang', categoryId: 'cartoon', description: 'Twanging spring' },
  { id: 'cartoon-8', name: 'Gulp', categoryId: 'cartoon', description: 'Exaggerated gulp' },
  { id: 'cartoon-9', name: 'Honk', categoryId: 'cartoon', description: 'Funny horn honk' },
  { id: 'cartoon-10', name: 'Squeak', categoryId: 'cartoon', description: 'Squeaky sound' },
  { id: 'cartoon-11', name: 'Crash', categoryId: 'cartoon', description: 'Comical crash' },
  { id: 'cartoon-12', name: 'Boing 2', categoryId: 'cartoon', description: 'Another spring bounce' },
  { id: 'cartoon-13', name: 'Slide Whistle', categoryId: 'cartoon', description: 'Sliding whistle effect' },
  { id: 'cartoon-14', name: 'Bonk', categoryId: 'cartoon', description: 'Hitting head sound' },
  { id: 'cartoon-15', name: 'Zing', categoryId: 'cartoon', description: 'Fast movement sound' },
  { id: 'cartoon-16', name: 'Splat 2', categoryId: 'cartoon', description: 'Another splat sound' },
  { id: 'cartoon-17', name: 'Boing 3', categoryId: 'cartoon', description: 'Third spring bounce' },
  { id: 'cartoon-18', name: 'Squish', categoryId: 'cartoon', description: 'Squishing sound' },
  { id: 'cartoon-19', name: 'Twirl', categoryId: 'cartoon', description: 'Spinning sound effect' },
  { id: 'cartoon-20', name: 'Poof', categoryId: 'cartoon', description: 'Disappearing poof' },
  
  // HORROR category
  { id: 'horror-1', name: 'Creaking Door', categoryId: 'horror', description: 'Eerie door creak' },
  { id: 'horror-2', name: 'Ghostly Whisper', categoryId: 'horror', description: 'Whispering voices' },
  { id: 'horror-3', name: 'Heartbeat', categoryId: 'horror', description: 'Intense heartbeat' },
  { id: 'horror-4', name: 'Scream', categoryId: 'horror', description: 'Blood-curdling scream' },
  { id: 'horror-5', name: 'Creepy Music Box', categoryId: 'horror', description: 'Distorted music box' },
  { id: 'horror-6', name: 'Demonic Laugh', categoryId: 'horror', description: 'Evil laughter' },
  { id: 'horror-7', name: 'Chains', categoryId: 'horror', description: 'Rattling chains' },
  { id: 'horror-8', name: 'Ghostly Moan', categoryId: 'horror', description: 'Moaning ghost' },
  { id: 'horror-9', name: 'Footsteps', categoryId: 'horror', description: 'Approaching footsteps' },
  { id: 'horror-10', name: 'Knife Sharpening', categoryId: 'horror', description: 'Knife on whetstone' },
  { id: 'horror-11', name: 'Creepy Child', categoryId: 'horror', description: 'Child singing' },
  { id: 'horror-12', name: 'Growl', categoryId: 'horror', description: 'Monster growling' },
  { id: 'horror-13', name: 'Scratching', categoryId: 'horror', description: 'Nails on wall' },
  { id: 'horror-14', name: 'Haunted Piano', categoryId: 'horror', description: 'Dissonant piano notes' },
  { id: 'horror-15', name: 'Dripping Blood', categoryId: 'horror', description: 'Blood dripping sound' },
  { id: 'horror-16', name: 'Creepy Ambience', categoryId: 'horror', description: 'Eerie atmosphere' },
  { id: 'horror-17', name: 'Zombie Groan', categoryId: 'horror', description: 'Undead groaning' },
  { id: 'horror-18', name: 'Witch Cackle', categoryId: 'horror', description: 'Witch laughing' },
  { id: 'horror-19', name: 'Bone Crack', categoryId: 'horror', description: 'Breaking bones' },
  { id: 'horror-20', name: 'Demonic Chant', categoryId: 'horror', description: 'Ritualistic chanting' },
  
  // SPORT category
  { id: 'sport-1', name: 'Crowd Cheer', categoryId: 'sport', description: 'Stadium crowd cheering' },
  { id: 'sport-2', name: 'Whistle', categoryId: 'sport', description: 'Referee whistle' },
  { id: 'sport-3', name: 'Ball Kick', categoryId: 'sport', description: 'Soccer ball being kicked' },
  { id: 'sport-4', name: 'Slam Dunk', categoryId: 'sport', description: 'Basketball slam dunk' },
  { id: 'sport-5', name: 'Home Run', categoryId: 'sport', description: 'Baseball home run hit' },
  { id: 'sport-6', name: 'Tennis Hit', categoryId: 'sport', description: 'Tennis racket hitting ball' },
  { id: 'sport-7', name: 'Golf Swing', categoryId: 'sport', description: 'Golf club swing' },
  { id: 'sport-8', name: 'Swimming Splash', categoryId: 'sport', description: 'Diving into water' },
  { id: 'sport-9', name: 'Boxing Bell', categoryId: 'sport', description: 'Boxing round bell' },
  { id: 'sport-10', name: 'Crowd Boo', categoryId: 'sport', description: 'Crowd booing' },
  { id: 'sport-11', name: 'Stadium Anthem', categoryId: 'sport', description: 'Stadium anthem snippet' },
  { id: 'sport-12', name: 'Crowd Wave', categoryId: 'sport', description: 'Crowd doing the wave' },
  { id: 'sport-13', name: 'Hockey Slap Shot', categoryId: 'sport', description: 'Hockey puck hit' },
  { id: 'sport-14', name: 'Bowling Strike', categoryId: 'sport', description: 'Bowling pins falling' },
  { id: 'sport-15', name: 'Volleyball Spike', categoryId: 'sport', description: 'Volleyball spike hit' },
  { id: 'sport-16', name: 'Skateboard Trick', categoryId: 'sport', description: 'Skateboard flip sound' },
  { id: 'sport-17', name: 'Karate Chop', categoryId: 'sport', description: 'Martial arts hit' },
  { id: 'sport-18', name: 'Racing Cars', categoryId: 'sport', description: 'Race cars passing by' },
  { id: 'sport-19', name: 'Gym Weights', categoryId: 'sport', description: 'Weights being dropped' },
  { id: 'sport-20', name: 'Victory Fanfare', categoryId: 'sport', description: 'Victory celebration' },
  
  // TECH category
  { id: 'tech-1', name: 'Computer Startup', categoryId: 'tech', description: 'System booting up' },
  { id: 'tech-2', name: 'Error Beep', categoryId: 'tech', description: 'Error notification' },
  { id: 'tech-3', name: 'Digital Blip', categoryId: 'tech', description: 'Digital interface sound' },
  { id: 'tech-4', name: 'Keyboard Typing', categoryId: 'tech', description: 'Fast typing on keyboard' },
  { id: 'tech-5', name: 'Laser Beam', categoryId: 'tech', description: 'Sci-fi laser firing' },
  { id: 'tech-6', name: 'Power Down', categoryId: 'tech', description: 'System shutting down' },
  { id: 'tech-7', name: 'Scanner', categoryId: 'tech', description: 'Digital scanning sound' },
  { id: 'tech-8', name: 'Dial Up', categoryId: 'tech', description: 'Old modem connecting' },
  { id: 'tech-9', name: 'Text Message', categoryId: 'tech', description: 'Message notification' },
  { id: 'tech-10', name: 'Digital Clock', categoryId: 'tech', description: 'Digital alarm beeping' },
  { id: 'tech-11', name: 'Hard Drive', categoryId: 'tech', description: 'Hard drive spinning' },
  { id: 'tech-12', name: 'Printer', categoryId: 'tech', description: 'Printer in action' },
  { id: 'tech-13', name: 'Camera Shutter', categoryId: 'tech', description: 'Digital camera click' },
  { id: 'tech-14', name: 'Server Room', categoryId: 'tech', description: 'Server room ambience' },
  { id: 'tech-15', name: 'Digital Glitch', categoryId: 'tech', description: 'Glitchy digital sound' },
  { id: 'tech-16', name: 'Sonar Ping', categoryId: 'tech', description: 'Submarine sonar ping' },
  { id: 'tech-17', name: 'Satellite', categoryId: 'tech', description: 'Satellite transmission' },
  { id: 'tech-18', name: 'Data Transfer', categoryId: 'tech', description: 'Data being transferred' },
  { id: 'tech-19', name: 'Drone', categoryId: 'tech', description: 'Drone flying sound' },
  { id: 'tech-20', name: 'Hacking', categoryId: 'tech', description: 'Hacking interface sounds' },
  
  // Add 20 effects for each remaining category
  // ROBOT category
  { id: 'robot-1', name: 'Robot Voice', categoryId: 'robot', description: 'Mechanical voice' },
  { id: 'robot-2', name: 'Servo Motor', categoryId: 'robot', description: 'Motor movement sound' },
  { id: 'robot-3', name: 'Robot Walk', categoryId: 'robot', description: 'Heavy robot footsteps' },
  { id: 'robot-4', name: 'Mechanical Arm', categoryId: 'robot', description: 'Robot arm movement' },
  { id: 'robot-5', name: 'Robot Beep', categoryId: 'robot', description: 'Robot communication beep' },
  { id: 'robot-6', name: 'Transformation', categoryId: 'robot', description: 'Robot transforming' },
  { id: 'robot-7', name: 'Robot Malfunction', categoryId: 'robot', description: 'Malfunctioning robot' },
  { id: 'robot-8', name: 'Robot Startup', categoryId: 'robot', description: 'Robot powering up' },
  { id: 'robot-9', name: 'Robot Shutdown', categoryId: 'robot', description: 'Robot powering down' },
  { id: 'robot-10', name: 'Robot Alert', categoryId: 'robot', description: 'Robot warning sound' },
  { id: 'robot-11', name: 'Robot Laugh', categoryId: 'robot', description: 'Mechanical laughter' },
  { id: 'robot-12', name: 'Robot Scan', categoryId: 'robot', description: 'Scanning environment' },
  { id: 'robot-13', name: 'Robot Dance', categoryId: 'robot', description: 'Dancing robot sounds' },
  { id: 'robot-14', name: 'Robot Battle', categoryId: 'robot', description: 'Robot fighting sounds' },
  { id: 'robot-15', name: 'Robot Factory', categoryId: 'robot', description: 'Factory assembly line' },
  { id: 'robot-16', name: 'Robot Pet', categoryId: 'robot', description: 'Mechanical pet sounds' },
  { id: 'robot-17', name: 'Robot Vacuum', categoryId: 'robot', description: 'Cleaning robot sound' },
  { id: 'robot-18', name: 'Robot Crush', categoryId: 'robot', description: 'Crushing metal sound' },
  { id: 'robot-19', name: 'Robot Hover', categoryId: 'robot', description: 'Hovering robot sound' },
  { id: 'robot-20', name: 'Robot Army', categoryId: 'robot', description: 'Multiple robots marching' },
  
  // FILM category
  { id: 'film-1', name: 'Dramatic Reveal', categoryId: 'film', description: 'Dramatic music sting' },
  { id: 'film-2', name: 'Suspense', categoryId: 'film', description: 'Suspenseful music' },
  { id: 'film-3', name: 'Action Scene', categoryId: 'film', description: 'Fast-paced action music' },
  { id: 'film-4', name: 'Romance Theme', categoryId: 'film', description: 'Romantic music' },
  { id: 'film-5', name: 'Western Standoff', categoryId: 'film', description: 'Western duel music' },
  { id: 'film-6', name: 'Sci-Fi Ambience', categoryId: 'film', description: 'Futuristic atmosphere' },
  { id: 'film-7', name: 'Horror Stinger', categoryId: 'film', description: 'Scary musical hit' },
  { id: 'film-8', name: 'Comedy Boing', categoryId: 'film', description: 'Funny sound effect' },
  { id: 'film-9', name: 'Sad Moment', categoryId: 'film', description: 'Melancholic music' },
  { id: 'film-10', name: 'Adventure Theme', categoryId: 'film', description: 'Adventurous music' },
  { id: 'film-11', name: 'Film Noir', categoryId: 'film', description: 'Detective film music' },
  { id: 'film-12', name: 'Space Battle', categoryId: 'film', description: 'Space warfare sounds' },
  { id: 'film-13', name: 'Heist Theme', categoryId: 'film', description: 'Sneaky heist music' },
  { id: 'film-14', name: 'Chase Scene', categoryId: 'film', description: 'Fast chase music' },
  { id: 'film-15', name: 'Flashback Harp', categoryId: 'film', description: 'Dreamy harp glissando' },
  { id: 'film-16', name: 'Superhero Theme', categoryId: 'film', description: 'Heroic fanfare' },
  { id: 'film-17', name: 'Villain Theme', categoryId: 'film', description: 'Evil character motif' },
  { id: 'film-18', name: 'Fantasy Magic', categoryId: 'film', description: 'Magical sound effect' },
  { id: 'film-19', name: 'War Scene', categoryId: 'film', description: 'Battle music' },
  { id: 'film-20', name: 'End Credits', categoryId: 'film', description: 'Closing theme music' },
  
  // DARK category
  { id: 'dark-1', name: 'Dark Ambient', categoryId: 'dark', description: 'Ominous atmosphere' },
  { id: 'dark-2', name: 'Deep Drone', categoryId: 'dark', description: 'Low frequency drone' },
  { id: 'dark-3', name: 'Dungeon Sounds', categoryId: 'dark', description: 'Echoing dungeon' },
  { id: 'dark-4', name: 'Eerie Wind', categoryId: 'dark', description: 'Haunting wind sound' },
  { id: 'dark-5', name: 'Dark Whispers', categoryId: 'dark', description: 'Whispering voices' },
  { id: 'dark-6', name: 'Ritual Chant', categoryId: 'dark', description: 'Dark ritual sounds' },
  { id: 'dark-7', name: 'Abandoned Place', categoryId: 'dark', description: 'Empty building ambience' },
  { id: 'dark-8', name: 'Nightmare', categoryId: 'dark', description: 'Disturbing dream sounds' },
  { id: 'dark-9', name: 'Dark Forest', categoryId: 'dark', description: 'Spooky forest at night' },
  { id: 'dark-10', name: 'Graveyard', categoryId: 'dark', description: 'Cemetery atmosphere' },
  { id: 'dark-11', name: 'Dark Water', categoryId: 'dark', description: 'Deep water sounds' },
  { id: 'dark-12', name: 'Cursed Music Box', categoryId: 'dark', description: 'Broken music box' },
  { id: 'dark-13', name: 'Dark Magic', categoryId: 'dark', description: 'Evil spell casting' },
  { id: 'dark-14', name: 'Haunted House', categoryId: 'dark', description: 'Haunted building sounds' },
  { id: 'dark-15', name: 'Dark Strings', categoryId: 'dark', description: 'Dissonant string section' },
  { id: 'dark-16', name: 'Void', categoryId: 'dark', description: 'Empty void atmosphere' },
  { id: 'dark-17', name: 'Catacombs', categoryId: 'dark', description: 'Underground tunnels' },
  { id: 'dark-18', name: 'Dark Breath', categoryId: 'dark', description: 'Heavy breathing' },
  { id: 'dark-19', name: 'Shadow Movement', categoryId: 'dark', description: 'Something moving in shadows' },
  { id: 'dark-20', name: 'Dark Presence', categoryId: 'dark', description: 'Unseen entity nearby' },
  
  // POP category
  { id: 'pop-1', name: 'Pop Beat', categoryId: 'pop', description: 'Catchy pop rhythm' },
  { id: 'pop-2', name: 'Pop Vocal', categoryId: 'pop', description: 'Pop vocal riff' },
  { id: 'pop-3', name: 'Pop Synth', categoryId: 'pop', description: 'Synthesizer melody' },
  { id: 'pop-4', name: 'Pop Bass', categoryId: 'pop', description: 'Funky bass line' },
  { id: 'pop-5', name: 'Pop Drums', categoryId: 'pop', description: 'Pop drum fill' },
  { id: 'pop-6', name: 'Pop Guitar', categoryId: 'pop', description: 'Guitar riff' },
  { id: 'pop-7', name: 'Pop Hook', categoryId: 'pop', description: 'Catchy musical hook' },
  { id: 'pop-8', name: 'Pop Chorus', categoryId: 'pop', description: 'Chorus section' },
  { id: 'pop-9', name: 'Pop Drop', categoryId: 'pop', description: 'EDM style drop' },
  { id: 'pop-10', name: 'Pop Clap', categoryId: 'pop', description: 'Rhythmic hand claps' },
  { id: 'pop-11', name: '80s Synth', categoryId: 'pop', description: 'Retro synthesizer' },
  { id: 'pop-12', name: '90s Beat', categoryId: 'pop', description: '90s style rhythm' },
  { id: 'pop-13', name: 'Pop Piano', categoryId: 'pop', description: 'Piano chord progression' },
  { id: 'pop-14', name: 'Pop Strings', categoryId: 'pop', description: 'String section' },
  { id: 'pop-15', name: 'Pop Brass', categoryId: 'pop', description: 'Brass section hit' },
  { id: 'pop-16', name: 'Dance Beat', categoryId: 'pop', description: 'Dance music rhythm' },
  { id: 'pop-17', name: 'Pop Percussion', categoryId: 'pop', description: 'Percussion loop' },
  { id: 'pop-18', name: 'Pop Intro', categoryId: 'pop', description: 'Song introduction' },
  { id: 'pop-19', name: 'Pop Outro', categoryId: 'pop', description: 'Song conclusion' },
  { id: 'pop-20', name: 'Pop Transition', categoryId: 'pop', description: 'Musical transition' },
  
  // WEIRD category
  { id: 'weird-1', name: 'Alien Language', categoryId: 'weird', description: 'Strange alien speech' },
  { id: 'weird-2', name: 'Backwards Audio', categoryId: 'weird', description: 'Reversed sound' },
  { id: 'weird-3', name: 'Glitch Noise', categoryId: 'weird', description: 'Digital glitching' },
  { id: 'weird-4', name: 'Time Stretch', categoryId: 'weird', description: 'Extremely slowed sound' },
  { id: 'weird-5', name: 'Pitch Shift', categoryId: 'weird', description: 'Bizarre pitch changes' },
  { id: 'weird-6', name: 'Underwater Voice', categoryId: 'weird', description: 'Submerged vocal effect' },
  { id: 'weird-7', name: 'Strange Creature', categoryId: 'weird', description: 'Unidentifiable creature' },
  { id: 'weird-8', name: 'Warped Reality', categoryId: 'weird', description: 'Reality distortion' },
  { id: 'weird-9', name: 'Interdimensional', categoryId: 'weird', description: 'Between dimensions' },
  { id: 'weird-10', name: 'Dream Sequence', categoryId: 'weird', description: 'Surreal dream sounds' },
  { id: 'weird-11', name: 'Bizarre Instrument', categoryId: 'weird', description: 'Unknown instrument' },
  { id: 'weird-12', name: 'Quantum Fluctuation', categoryId: 'weird', description: 'Quantum physics sound' },
  { id: 'weird-13', name: 'Psychedelic', categoryId: 'weird', description: 'Mind-bending audio' },
  { id: 'weird-14', name: 'Impossible Sound', categoryId: 'weird', description: 'Physically impossible sound' },
  { id: 'weird-15', name: 'Consciousness Shift', categoryId: 'weird', description: 'Awareness changing' },
  { id: 'weird-16', name: 'Parallel Universe', categoryId: 'weird', description: 'Alternate reality' },
  { id: 'weird-17', name: 'Time Loop', categoryId: 'weird', description: 'Repeating time fragment' },
  { id: 'weird-18', name: 'Void Echo', categoryId: 'weird', description: 'Echo from nothingness' },
  { id: 'weird-19', name: 'Thought Sound', categoryId: 'weird', description: 'Sound of thinking' },
  { id: 'weird-20', name: 'Reality Glitch', categoryId: 'weird', description: 'Reality breaking down' },
];

// Helper function to get effects by category
export const getEffectsByCategory = (categoryId: string): AudioEffect[] => {
  return audioEffects.filter(effect => effect.categoryId === categoryId);
};